// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCsAFpLPHPJoludzJDxXPa1EjfeJfx9a8',
    appId: '1:501020276381:web:778944fe3e15ecb9d90674',
    messagingSenderId: '501020276381',
    projectId: 'mynotes-7bcaa',
    authDomain: 'mynotes-7bcaa.firebaseapp.com',
    storageBucket: 'mynotes-7bcaa.appspot.com',
    measurementId: 'G-7NYCYR3QRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABmO2cV9-H2lyw4Fd0Rzxp-nAMC_SbuVo',
    appId: '1:501020276381:android:cb21a9c52a013da0d90674',
    messagingSenderId: '501020276381',
    projectId: 'mynotes-7bcaa',
    storageBucket: 'mynotes-7bcaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbpflKNxGHcBwX7lg-E0XVcGGWMYIN8iM',
    appId: '1:501020276381:ios:257ece1f314305d9d90674',
    messagingSenderId: '501020276381',
    projectId: 'mynotes-7bcaa',
    storageBucket: 'mynotes-7bcaa.appspot.com',
    iosClientId: '501020276381-oh0ijdqd1qhqt9pean5ram1hc1kb7dpi.apps.googleusercontent.com',
    iosBundleId: 'com.musnguyen.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbpflKNxGHcBwX7lg-E0XVcGGWMYIN8iM',
    appId: '1:501020276381:ios:257ece1f314305d9d90674',
    messagingSenderId: '501020276381',
    projectId: 'mynotes-7bcaa',
    storageBucket: 'mynotes-7bcaa.appspot.com',
    iosClientId: '501020276381-oh0ijdqd1qhqt9pean5ram1hc1kb7dpi.apps.googleusercontent.com',
    iosBundleId: 'com.musnguyen.mynotes',
  );
}
